#!/bin/bash
#
# Backup mysql/mariadb database
 
## Get current date ##
_now=$(date +"%m_%d_%Y")
 
## Appending a current date from a $_now to a filename stored in $_file ##
_file="log_$_now.log"
 
## Do it ##
echo "Starting log to $_file..."
mvn -e clean deploy -Dmaven.test.skip=true > "$_file"

